version: "3.9"
services:
  db:
    image: nouchka/sqlite3
    volumes:
      - ./db:/usr/src/app/db
    restart: always
  app:
    container_name: subscribers-app
    build: .
    ports:
      - '8081:3000'
    environment:
      NODE_ENV: production
    volumes:
      - ./db:/usr/src/app/db
    restart: always
